setwd("~/Documents/edX/Analytics Edge/Kaggle")
ebayTrain = read.csv("eBayiPadTrain.csv", stringsAsFactors = FALSE)
str(ebayTrain)
library(caTools)
library(visreg)
set.seed(2575)
spl = sample.split(ebayTrain$sold, SplitRatio = 0.85)
ebayTrain_TrainSubset = subset(ebayTrain, spl == TRUE)
ebayTrain_TestSubset = subset(ebayTrain, spl == FALSE)
ebayTest = read.csv("eBayiPadTest.csv", stringsAsFactors = FALSE)
str(ebayTest)
model1 = glm(sold ~ ., data = ebayTrain_TrainSubset, family = binomial)
#summary(model1)
str(ebayTrain_TrainSubset)
model2 = glm(sold ~ . - description - cellular - color , data = ebayTrain_TrainSubset, family = binomial)
summary(model2)
model3 = glm(sold ~ biddable + startprice + productline, data = ebayTrain_TrainSubset, family = binomial)
summary(model3)
library(ROCR)
TrainPredModel3 = predict(model3, type = "response")
ROCPredTrain3 = prediction(TrainPredModel3, ebayTrain_TrainSubset$sold)
as.numeric(performance(ROCPredTrain3, "auc")@y.values)
TestPredModel3 = predict(model3, newdata = ebayTrain_TestSubset, type = "response")
ROCPredTest3 = prediction(TestPredModel3, ebayTrain_TestSubset$sold)
as.numeric(performance(ROCPredTest3, "auc")@y.values)
TrainPredModel2 = predict(model2, type = "response")
ROCPredTrain2 = prediction(TrainPredModel2, ebayTrain_TrainSubset$sold)
as.numeric(performance(ROCPredTrain2, "auc")@y.values)
TestPredModel2 = predict(model2, newdata = ebayTrain_TestSubset, type = "response")
TestNew = predict(model3, newdata = ebayTest, type = "response")
MySubmission = data.frame(UniqueID = ebayTest$UniqueID, Probability1 = TestNew)
write.csv(MySubmission, "SubmissionDescription.csv", row.names = FALSE)