setwd("~/Documents/edX/Analytics Edge/Kaggle")
ebayTest = read.csv("ebayiPadTest.csv", stringsAsFactors = FALSE)
ebayTrain = read.csv("ebayiPadTrain.csv", stringsAsFactors = FALSE)
library(tm)
CorpusDescription = Corpus(VectorSource(c(ebayTrain$description, ebayTest$description)))
CorpusDescription = tm_map(CorpusDescription, content_transformer(tolower), lazy = TRUE)
CorpusDescription = tm_map(CorpusDescription, PlainTextDocument, lazy = TRUE)
CorpusDescription = tm_map(CorpusDescription, removePunctuation, lazy = TRUE)
CorpusDescription = tm_map(CorpusDescription, removeWords, stopwords("english"), lazy = TRUE)
CorpusDescription = tm_map(CorpusDescription, stemDocument, lazy = TRUE)
dtm = DocumentTermMatrix(CorpusDescription)
sparse = removeSparseTerms(dtm, 0.99)
DescriptionWords = as.data.frame(as.matrix(sparse))
colnames(DescriptionWords) = make.names(colnames(DescriptionWords))
DescriptionWordsTrain = head(DescriptionWords, nrow(ebayTrain))
DescriptionWordsTest = tail(DescriptionWords, nrow(ebayTest))
DescriptionWordsTrain$sold = ebayTrain$sold
str(DescriptionWordsTrain)
DescriptionWordsLog = glm(sold ~ ., data = DescriptionWordsTrain, family = binomial)
PredTest = predict(DescriptionWordsLog, newdata = DescriptionWordsTest, type = "response")
MySubmission = data.frame(UniqueID = ebayTest$UniqueID, Probability1 = PredTest)
write.csv(MySubmission, "SubmissionDescription.csv", row.names = FALSE)
